### ISSUE TITLE
Make strict stubs the default setting for TestNGListener

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-testng#1]
Mockito is converging on using strict stubbing mechanism so let's configure TestNGListener to also use strict stubs by default.

Strict stubbing in Mockito:
 - default for JUnit5 Mockito
 - default for MockitoSession API
 - planned as default for Mockito 3 for JUnit 4 rules + runners

Since TestNG integration is not announced yet, and it has 0.* version, it is ok to update the defaults now.

Thoughts/feedback?

**Comment by mouyang** [comment]
I have both JUnit 4 and TestNG 6 unit tests using Mockito 2.  I transitioned the JUnit tests to use the JUnit 4 rules seamlessly, but I was not able to do the same with the TestNG listener because it uses a different setting for default strictness.  I also wanted to limit the scope of my code commits and therefore did not want to introduce fixes for strict stubs right away, which the JUnit default allowed.  My options to fix the strict stub issues, had I chosen to do so, were limited or tedious.

In the case of Mockito 2, I found the leap from lenient to strict stubs in TestNG to be too great in practice to proceed.  The default settings should be consistent across all platforms within a major version, and I don't think the lack of an official TestNG integration announcement justifies changing the default.

But since I came too late to this discussion, what should be done now?  Should this project have release branches split by major version like mockito/mockito?  Is it too late to change the default strictness to warn in order to match Mockito 2 and JUnit 4 rules+runners?  Does it make sense for TestNG integration to be Mockito 2 only until Mockito 3 is ready?  Please advise.
